// DoseTrack/Services/ReportGenerator.swift
// Pro feature — gated at the call site before this is invoked.
import PDFKit
import UIKit
import CoreData

final class ReportGenerator {

    static let shared = ReportGenerator()
    private init() {}

    // MARK: - PDF Doctor Report

    func generatePDF(
        logs: [DoseLog],
        medications: [Medication],
        dateRange: DateInterval,
        patientName: String
    ) -> Data {
        let pageWidth: CGFloat = 612   // US Letter points
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 60
        let contentWidth = pageWidth - margin * 2

        let pdfData = NSMutableData()
        UIGraphicsBeginPDFContextToData(pdfData, CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight), nil)
        UIGraphicsBeginPDFPage()

        var yOffset: CGFloat = margin

        // Header
        yOffset = drawText(
            "Medication Adherence Report",
            at: CGPoint(x: margin, y: yOffset),
            width: contentWidth,
            font: .systemFont(ofSize: 20, weight: .bold),
            color: .black
        )
        yOffset += 4
        yOffset = drawText(
            "Generated by DoseTrack · \(Date().formatted(date: .long, time: .omitted))",
            at: CGPoint(x: margin, y: yOffset),
            width: contentWidth,
            font: .systemFont(ofSize: 11),
            color: .darkGray
        )

        // Patient info
        yOffset += 16
        drawHRule(at: yOffset, margin: margin, width: contentWidth)
        yOffset += 8
        if !patientName.isEmpty {
            yOffset = drawText(
                "Patient: \(patientName)",
                at: CGPoint(x: margin, y: yOffset),
                width: contentWidth,
                font: .systemFont(ofSize: 12, weight: .medium),
                color: .black
            )
        }

        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        let rangeText = "\(formatter.string(from: dateRange.start)) – \(formatter.string(from: dateRange.end))"
        yOffset = drawText(
            "Report period: \(rangeText)",
            at: CGPoint(x: margin, y: yOffset),
            width: contentWidth,
            font: .systemFont(ofSize: 12),
            color: .darkGray
        )

        // Overall adherence summary
        yOffset += 16
        let totalLogs = logs.count
        let takenLogs = logs.filter { $0.doseStatus == .taken }.count
        let overallPct = totalLogs > 0 ? Int(Double(takenLogs) / Double(totalLogs) * 100) : 100
        yOffset = drawText(
            "Overall adherence: \(overallPct)%  (\(takenLogs) of \(totalLogs) doses taken)",
            at: CGPoint(x: margin, y: yOffset),
            width: contentWidth,
            font: .systemFont(ofSize: 13, weight: .semibold),
            color: .black
        )

        // Per-medication table
        yOffset += 16
        drawHRule(at: yOffset, margin: margin, width: contentWidth)
        yOffset += 8

        yOffset = drawText(
            "Per-Medication Breakdown",
            at: CGPoint(x: margin, y: yOffset),
            width: contentWidth,
            font: .systemFont(ofSize: 14, weight: .bold),
            color: .black
        )
        yOffset += 8

        let colWidths: [CGFloat] = [contentWidth * 0.45, contentWidth * 0.15, contentWidth * 0.15, contentWidth * 0.15, contentWidth * 0.10]
        let headers = ["Medication", "Dose", "Taken", "Total", "%"]

        // Table header row
        var x = margin
        for (i, header) in headers.enumerated() {
            drawText(header, at: CGPoint(x: x, y: yOffset), width: colWidths[i],
                     font: .systemFont(ofSize: 10, weight: .bold), color: .darkGray)
            x += colWidths[i]
        }
        yOffset += 16
        drawHRule(at: yOffset, margin: margin, width: contentWidth, lineWidth: 0.5, color: .lightGray)
        yOffset += 4

        // Table rows
        for med in medications.sorted(by: { $0.wrappedName < $1.wrappedName }) {
            let medLogs = logs.filter { $0.medication == med }
            guard !medLogs.isEmpty else { continue }

            if yOffset > pageHeight - margin * 2 {
                UIGraphicsBeginPDFPage()
                yOffset = margin
            }

            let taken = medLogs.filter { $0.doseStatus == .taken }.count
            let total = medLogs.count
            let pct = total > 0 ? Int(Double(taken) / Double(total) * 100) : 100

            let values = [med.wrappedName, "\(med.wrappedDosage) \(med.wrappedUnit)", "\(taken)", "\(total)", "\(pct)%"]
            x = margin
            for (i, value) in values.enumerated() {
                drawText(value, at: CGPoint(x: x, y: yOffset), width: colWidths[i],
                         font: .systemFont(ofSize: 10), color: .black)
                x += colWidths[i]
            }
            yOffset += 16
        }

        // Footer disclaimer
        yOffset = pageHeight - margin - 30
        drawHRule(at: yOffset, margin: margin, width: contentWidth)
        yOffset += 6
        drawText(
            "This report is a reminder tool record only and does not constitute medical advice. Always follow your healthcare provider's instructions.",
            at: CGPoint(x: margin, y: yOffset),
            width: contentWidth,
            font: .systemFont(ofSize: 8),
            color: .gray
        )

        UIGraphicsEndPDFContext()
        return pdfData as Data
    }

    // MARK: - Drawing helpers

    @discardableResult
    private func drawText(
        _ text: String,
        at point: CGPoint,
        width: CGFloat,
        font: UIFont,
        color: UIColor
    ) -> CGFloat {
        let attrs: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: color
        ]
        let str = NSAttributedString(string: text, attributes: attrs)
        let rect = CGRect(x: point.x, y: point.y, width: width, height: 1000)
        let bounds = str.boundingRect(with: CGSize(width: width, height: 1000),
                                       options: [.usesLineFragmentOrigin], context: nil)
        str.draw(in: rect)
        return point.y + bounds.height + 2
    }

    private func drawHRule(
        at y: CGFloat,
        margin: CGFloat,
        width: CGFloat,
        lineWidth: CGFloat = 1,
        color: UIColor = .black
    ) {
        color.setStroke()
        let path = UIBezierPath()
        path.lineWidth = lineWidth
        path.move(to: CGPoint(x: margin, y: y))
        path.addLine(to: CGPoint(x: margin + width, y: y))
        path.stroke()
    }
}
